# My extra setting
encoding: UTF-8

excerpt_separator: <!--excerpt-->

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Jax"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Jax"
  -
    scope:
      path: "_drafts"
      # type: "drafts"
    values:
      layout: "post"
      author: "Jax"

exclude:
  - README.md

# Original setting
title: 叫我贾克思就好
author:
  name: Jax Young
  email: jaxvanyang@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Kepp It Simple and Stupid.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y %b %-d"
  skin: dark

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  jaxvanyang
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
